name: Deploy Flask App to AWS EC2

on:
  push:
    branches:
      - main
      - dev
      - test

jobs:
  local-test:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and run Docker container locally
      run: |
        docker build . -t project_cicd
        docker run -d -p 5000:5000 project_cicd
        sleep 10
        curl --fail http://localhost:5000/generate-password?length=24

  deploy-to-ec2:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1

    - name: Launch EC2 instance
      id: ec2
      run: |
        INSTANCE_ID=$(aws ec2 run-instances \
          --image-id ami-053b0d53c279acc90 \
          --instance-type t3.micro \
          --key-name ${{ secrets.KEY_PAIR_NAME }} \
          --security-group-ids sg-03311b57e0cda8d74 \
          --subnet-id subnet-090d5f4dd3137a324 \
          --associate-public-ip-address \
          --query 'Instances[0].InstanceId' \
          --output text)
        echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
        aws ec2 wait instance-running --instance-ids $INSTANCE_ID
        PUBLIC_IP=$(aws ec2 describe-instances \
          --instance-ids $INSTANCE_ID \
          --query 'Reservations[0].Instances[0].PublicIpAddress' \
          --output text)
        echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

    - name: Wait for EC2 to be ready
      run: |
        sleep 30
        for i in $(seq 1 5); do
          nc -zv ${{ env.PUBLIC_IP }} 22 && break
          echo "Waiting for SSH..."
          sleep 10
        done

    - name: Deploy Flask app via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ env.PUBLIC_IP }}
        username: ubuntu
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo docker pull 239847234/project_cicd:tagname
          sudo docker run -d -p 5000:5000 239847234/project_cicd:tagname

    - name: Test the app
      run: |
        sleep 15
        curl http://${{ env.PUBLIC_IP }}:5000/generate-password?length=24

